### ISSUE TITLE
Docker image link not working

### ISSUE THREAD

**Issue by ssantic** [jonathandinu/data-engineering-101#5]
The link for the instructions for pulling down the Docker image (under Setup) is dead.

**Comment by femibyte** [comment]
Yeah, where can I find the image?

**Comment by hopelessoptimism** [comment]
For the workshop, I opted to not use docker since it was simple enough to get people up and running with their own environments. I will remove the link from the description, I would recommend installing the required libraries with Anaconda: https://www.youtube.com/watch?v=Ny2X_WNxrB4

**Comment by jonathandinu** [comment]
I am overhauling the resources for 2021 and will make a new Docker image to streamline everything. Hang tight and I'll be adding some much needed updates!
