### ISSUE TITLE
abstract-rendering install fails due to dependency on numpy

### ISSUE THREAD

**Issue by DrOzturk** [jonathandinu/data-engineering-101#6]
Is this an issue with my configuration?
I created a fresh virtual env, activated it  and then, install fails:
> pip install -r requirements.txt
Collecting abstract-rendering==0.5.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d1/5d/dce48d00a215bfe8c0e5ff7fe2617bef5dca4e23e575b81369fb1aff1f20/abstract_rendering-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p0/d46h28z150n14vdy_tnrg2nc0000gp/T/pip-install-opEghw/abstract-rendering/setup.py", line 6, in <module>
        from numpy import get_include
    ImportError: No module named numpy

**Comment by jonathandinu** [comment]
The repo is old enough that the dependencies and environment are likely very out of date. I am working now to make a new Docker image and m going to update these resources for 2021
