### ISSUE TITLE
app.py needs ipdb module

### ISSUE THREAD

**Issue by DrOzturk** [jonathandinu/data-engineering-101#8]
app.py giving error.
I assumed this docker image contains all needed.
I gives error:

cd /root/workshop/
root@994a60f089ae:~/workshop# ipython2 app.py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/root/workshop/app.py in <module>()
      1 from flask import render_template, Flask, request, Response
----> 2 import ipdb
      3 import json
      4 import pickle
      5 import numpy as np

ImportError: No module named ipdb

**Comment by jonathandinu** [comment]
see #6
